name: Publish

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
        name: Checkout
      - uses: actions/setup-node@v2.1.5
        name: Setup Node.js environment
      - run: npm install
        name: Install Node dependencies
      - run: npm build
        name: Build typescript
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        name: Publish package
